### ISSUE TITLE
zio-2.0.0-RC6

### ISSUE THREAD

**Issue by domdorn** [senia-psm/zio-test-akka-http#153]
Hi!

What are your plans regarding RC6 or later in light of https://github.com/zio/zio/issues/6768 ?

**Comment by senia-psm** [comment]
I'll reimplement `RouteTestResult` to work with `Assertion`. Unfortunately it's no as straight forward as in migration guide.
I'll give it a try this weekend.

**Comment by domdorn** [comment]
actually I'm drafting an API like the above right now.. at the moment I have added these implicit classes to my code:
```scala
  implicit class RouteTestResultAdditions(z: URIO[Environment with System, RouteTestResult]) {
    def completed: ZIO[RouteTestEnvironment.TestEnvironment with _root_.zio.test.environment.TestEnvironment with System, NoSuchElementException, RouteTestResult.Completed] = z.collect(new NoSuchElementException("response is not a completed")) {
      case x: RouteTestResult.Completed => x
    }

    def timeout = z.collect(new NoSuchElementException("response did not timeout")) {
      case x@RouteTestResult.Timeout => x
    }

    def rejected = z.collect(new NoSuchElementException("request did not get rejected")) {
      case x: RouteTestResult.Rejected => x
    }

  }

  implicit class ResponseEntityAdditions(z: ResponseEntity) {

    def strict = for {
      mat <- ZIO.service[Materializer]
      strictEntity <- ZIO.fromFuture(ec => z.toStrict(FiniteDuration(1, scala.concurrent.duration.SECONDS))(mat))
    } yield strictEntity

    val bodyAsString = for {
      strictEntity <- strict
      s = strictEntity.data.utf8String
    } yield s



  }
```

which already allows me to write tests like this:
```scala
    testM("should return a response for /api/v1/users/userInfo when viopt credentials given") {
      for {
        _ <- ZIO.unit
        routes <- ZIO.service[WebModule]
        request = HttpRequest(
          HttpMethods.GET,
          "/api/v1/users/userInfo"
        ).mapHeaders(seq => seq ++ Seq(Authorization(TestTokens.OAuthTokens.Administrator: HttpCredentials)))
        handledReq <- (request ~> routes.route).completed
        response <- handledReq.response
        status = response.status
        test1 = assertTrue(status == StatusCodes.OK)
        body <- response.entity.bodyAsString
        test2 = assertTrue(UserId("tester@acme.inet").toString == body)
      } yield test1 && test2
    },
```

I'll continue a little and will share what I've came up with.

**Comment by senia-psm** [comment]
@domdorn  unfortunately this is not an optimal from usability point of view: `handledReq <- (request ~> routes.route).completed`. There are better ways to implement this.
First of all we have to preserve `assertTrue` error messages. All possible errors should be handled by `assertTrue` macros, not by errors in `ZIO`. Errors in `ZIO` are incompatible with `check`.

1. Use `Option` for integration with `assertTrue` macros:
```scala
def completed: Option[RouteTestResult.Completed]

assertTrue(response.completed.get.status == StatusCodes.OK)
```
2. Use smart assertions approach like this: https://github.com/zio/zio/pull/5492

Unfortunately this means we need 2 kinds of `RouteTestResult`: eager and lazy. Lazy result should not fetch response body (for infinite responses) and eager result should fetch body right away to avoid effects in `assertTrue`.
