### ISSUE TITLE
1.0.15: `EagerCompleted` is missing headers / `Content-Type` header

### ISSUE THREAD

**Issue by domdorn** [senia-psm/zio-test-akka-http#159]
When migrating my tests from version `1.0.3` to `1.0.15` I've experienced the following behavior:
The following code fails cause no headers or at least not the `Content-Type` header get populated in the `Completed` /  `EagerCompleted`:

```scala
 def getNextCalcIdWithAssertions(r: RouteTestResult): ZIO[Any, Serializable, (Some[(JobId, CalcId)], Assert)] = for {
    v <- ZIO.fromOption(r.handled)
    statusCheck = assertTrue(v.status == StatusCodes.OK)
    _ <- ZIO.debug(v.headers)
    contentTypeCheck = assertTrue(v.header("Content-Type").get.value() == "application/json") // <- this fails
    completed = v.asInstanceOf[EagerCompleted]
    response <- ZIO.fromEither(completed.responseAs[GetNextCalcController.Response])
    ...
```

I haven't tested if other headers are also missing, but at least the `Content-Type` header is missing. 

![grafik](https://user-images.githubusercontent.com/100349/175342935-dc82e6bb-54ef-4dce-8c00-6a8406564376.png)

I found a workaround: directly use the `contentType` property on `EagerCompleted`. 
However, this breaks some existing user tests (at least in my codebase) and is unexpected behavior.

**Comment by senia-psm** [comment]
@domdorn this is consistent with `akka-http-testkit`:

```scala
Get() ~> smallRoute ~> check {
  contentType shouldEqual ContentTypes.`text/plain(UTF-8)`
  headers shouldEqual Seq()
}
```

With this behaviour you can check that content type is not specified manually by directives, but instead inferred from entity.
`headers` is only for headers provided by directives.

I'd prefer to keep behaviour aligned to `akka-http-testkit`.

**Comment by domdorn** [comment]
thanks for clarifying. will update my tests accordingly (we've used the contentType matcher before)
