### ISSUE TITLE
Provide way to use custom typesafe config

### ISSUE THREAD

**Issue by domdorn** [senia-psm/zio-test-akka-http#224]
I need to store some custom configuration in my typesafe config. 
Unfortunatelly, its not clear to me, how I can make the testkit use my own config. 
I found that there is a `def testConfigSource: String = ""` in the `RouteTestEnvironment` Companion object 
but its not clear to me how to use/override it so I can provide my own config. 

it would be great if you could provide a small testcase that shows how to do that - Thanks!

**Comment by domdorn** [comment]
At the moment I have a workaround like 

```scala
object FallbackZioDirectivesSpec extends ZIOSpecDefault with RouteTest {

  val testLayer = testEnvironment >+> (RouteTestEnvironment.testSystemFromConfig >>> ((ZLayer
    .environment[ActorSystem] ++ testMaterializer) ++ RouteTest.testConfig))

  val akkaConfig = ZLayer.succeed[Config](
    ConfigFactory
      .parseString(s"""
      |myCustomSettings...
      |""".stripMargin)
      .withFallback(ConfigFactory.load()))
      
      override def spec: Spec[TestEnvironment with Scope, Any] = ...
       .provide(
      otherDependencies,
      testLayer,
      akkaConfig
    )
    
 ```
 
 
 If `RouteTestEnvironment` would be a `trait` mixed into `AkkaZIOSpecDefault` I think it would be easier to override.

**Comment by senia-psm** [comment]
You can use `test/resources/application.conf` for akka config.

BTW: your `testLayer` can be simplified:

```
ZLayer.makeSome[Config, TestEnvironment](
      testSystemFromConfig,
      testMaterializer,
      RouteTest.testConfig
  )
```

I'll add such layer to `RouteTestEnvironment`.

**Comment by senia-psm** [comment]
See https://github.com/senia-psm/zio-test-akka-http/releases/tag/2.0.14
