### ISSUE TITLE
provide more examples

### ISSUE THREAD

**Issue by domdorn** [senia-psm/zio-test-akka-http#96]
I'm having a really hard time figuring out how to use this library. 
e.g. I have a request and just want to verify that the response code is accepted and the body equals some string and it seems impossible to do this without providing the whole HttpResponse the server is sending (which would then have to match fully)

e.g. 
```scala
object HooksIntegrationTests extends DefaultAkkaRunnableSpec {

  override def spec = suite("HooksIntegrationSpec")(
    testM("blabla")(
      for {
        module <- ZIO.service[HooksWebModule]
        request = HttpRequest(
          HttpMethods.POST,
          "/api/hooks/webtsm/published",
          entity = HttpEntity.Strict(
            ContentTypes.`application/json`, {
              val json =
                s"""
                   |{[
                   |{"ID":1529,
                   |"Name":"Speichermaschinensatz
                   |"Status":201,
                   |"Message":"Time series data successfully saved.",
                   |"Details":null
                   |}
                   |]
                   |}
                   |""".stripMargin
              ByteString(json)
            }
          )
        )

        x <- assertM(request ~> module.routes)(
          handled(
            status(equalTo(StatusCodes.Accepted)) && responseAs[String](equalTo("my controller response text")) // this does not work
          )
        )
      } yield assertTrue(true) && x
    )
  ).provideSomeLayer[ZEnv with ZTestEnv with Annotations with RouteTestEnvironment.TestEnvironment with TestEnvironment](HooksWebModule.live)

```

In general, I would wish some helper methods I could just use with the normal Object.accessor pattern..

**Comment by senia-psm** [comment]
@domdorn at the moment it's impossible to implement something similar to `assertTrue(response.statusCode == OK)` for these tests - we stuck with `assertM`.

The reason for than is that `assertTrue` works only with pure assertions, but `handled` and all other assertions for akka-http are effectful. I'll try to reimplement assertions in `assertTrue` style after `zio 2.0` release.

BTW: you don't need `yield assertTrue(true) && x` - `yield x` should be fine.

**Comment by senia-psm** [comment]
@domdorn see https://github.com/senia-psm/zio-test-akka-http/pull/154
